// Run from the repository root: dart run tool/build_wordlists.dart [--check]
// FrequencyWords MIT source: tool/raw/freq_ar_50k.txt (see curated/README.md).
// Answers are always explicitly curated; generation never selects answers.
import 'dart:io';

import 'package:kalimat/game/engine/game_rules.dart';
import 'package:kalimat/game/engine/letters.dart';
import 'package:kalimat/game/engine/puzzle_calendar.dart';

List<String> readWords(String path) => File(path)
    .readAsLinesSync()
    .map((line) => line.trim())
    .where((line) => line.isNotEmpty && !line.startsWith('#'))
    .toList();

/// All validation happens before any generated file is written.
Map<String, String> generateWordlists() {
  final dictionary = <String>{};
  for (final line in File('tool/raw/freq_ar_50k.txt').readAsLinesSync()) {
    final parts = line.trim().split(RegExp(r'\s+'));
    if (parts.length != 2 || int.tryParse(parts[1]) == null) continue;
    final word = stripMarks(parts.first);
    if (isPlayableWord(word)) dictionary.add(normalizeWord(word));
  }
  for (final word in readWords('tool/curated/guess_additions.txt')) {
    if (!isPlayableWord(word)) {
      throw StateError('Invalid reviewed guess: $word');
    }
    dictionary.add(normalizeWord(word));
  }
  final seen = <String>{};
  List<String> answers(String path, int count) {
    final words = readWords(path);
    if (words.length != count) {
      throw StateError('$path: expected $count answers, got ${words.length}');
    }
    for (final (index, word) in words.indexed) {
      final location = '$path answer ${index + 1}: $word';
      if (!isPlayableWord(word)) {
        throw StateError('$location: invalid letters/length');
      }
      final normalized = normalizeWord(word);
      if (!dictionary.contains(normalized)) {
        throw StateError('$location: not in dictionary');
      }
      if (!seen.add(normalized)) {
        throw StateError('$location: duplicate across answer pools');
      }
    }
    return words;
  }

  final daily = answers('assets/words/answers.txt', 365);
  final duels = answers('tool/curated/duel_answers.txt', 200);
  final sorted = dictionary.toList()..sort();
  final dailySeed = StringBuffer()
    ..writeln('-- Generated by tool/build_wordlists.dart. Do not edit.')
    ..writeln(
      '-- Puzzle 1 = ${dateForPuzzle(1).toIso8601String().substring(0, 10)}; order matches bundled answers.',
    )
    ..writeln(
      'insert into public.daily_words (word_date, puzzle_no, word) values',
    );
  for (final (i, word) in daily.indexed) {
    final date = dateForPuzzle(i + 1).toIso8601String().substring(0, 10);
    dailySeed.writeln(
      "('$date', ${i + 1}, '$word')${i == daily.length - 1 ? '' : ','}",
    );
  }
  dailySeed.writeln(
    'on conflict (word_date) do update set word = excluded.word, puzzle_no = excluded.puzzle_no;',
  );
  final duelSeed = StringBuffer()
    ..writeln('-- Generated by tool/build_wordlists.dart. Do not edit.')
    ..writeln(
      '-- Reviewed duel answers; normalized spellings disjoint from daily answers.',
    )
    ..writeln('insert into public.challenge_words (word) values');
  for (final (i, word) in duels.indexed) {
    duelSeed.writeln("('$word')${i == duels.length - 1 ? '' : ','}");
  }
  duelSeed.writeln('on conflict (word) do nothing;');
  return {
    'assets/words/dictionary.txt': '${sorted.join('\n')}\n',
    'supabase/seed/daily_words_seed.sql': dailySeed.toString(),
    'supabase/seed/challenge_words_seed.sql': duelSeed.toString(),
  };
}

void main(List<String> args) {
  if (args.any((arg) => arg != '--check')) {
    throw ArgumentError('Usage: dart run tool/build_wordlists.dart [--check]');
  }
  final outputs = generateWordlists();
  for (final entry in outputs.entries) {
    final file = File(entry.key);
    if (args.contains('--check')) {
      if (!file.existsSync() || file.readAsStringSync() != entry.value) {
        throw StateError('${entry.key} is stale; regenerate word lists');
      }
    } else {
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(entry.value);
    }
  }
  stdout.writeln(
    'Validated 365 daily + 200 disjoint duel answers; '
    '${outputs.values.first.trim().split('\n').length} accepted guesses. '
    '${args.contains('--check') ? 'Generated files match.' : 'Generated dictionary and SQL seeds.'}',
  );
}
